# Generated by Django 5.2.1 on 2025-05-25 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_color', models.ImageField(upload_to='brand_image/')),
                ('brand_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=10, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=32)),
                ('car_name_en', models.CharField(max_length=32, null=True)),
                ('car_name_ru', models.CharField(max_length=32, null=True)),
                ('car_name_ky', models.CharField(max_length=32, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rul', models.CharField(choices=[('left', 'left'), ('right', 'right')], max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('city_en', models.CharField(max_length=32, null=True)),
                ('city_ru', models.CharField(max_length=32, null=True)),
                ('city_ky', models.CharField(max_length=32, null=True)),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('car_video', models.FileField(blank=True, null=True, upload_to='car_videos', verbose_name='Видео')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.carmodel')),
            ],
        ),
    ]
